# Generated by Django 4.1.7 on 2023-02-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_Appl', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_Eve', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='lof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lof_fol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='loginpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginpage_Username', models.CharField(max_length=50)),
                ('loginpage_Email', models.EmailField(max_length=254, verbose_name='')),
                ('loginpage_Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_Notice', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_Hostel', models.CharField(max_length=50)),
                ('profile_HostelBlock', models.CharField(max_length=20)),
                ('profile_RoomNo', models.IntegerField(max_length=10)),
                ('profile_contact', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queries_Query', models.CharField(max_length=900)),
            ],
        ),
    ]
